export {default as Posts} from './Posts'
export {default as Navbar} from './Navbar'
export {default as NewPost} from './Newpost'
export {default as Profile} from './Profile'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as SinglePost} from './SinglePost'